-- Read-only. Run in the intended TEST connection; enter an approved test material.
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV', 'SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME
FROM DUAL;

-- Compare these values before/after a QA file. Existing materials change only flag/modify date.
SELECT PLNT, SLOC, MATERIAL, MTYP, OLD_MATERIAL_NO, MATERIAL_DESCRIPTION,
       MATL_GROUP, BUN, PGR, BASIC_MATERIAL, BIN, STANDARD_PRICE, SMI2, SPQ,
       SPECIAL_CONTROL_FLAG, CREATE_DATE, MODIFY_DATE
FROM MATERIAL.MAT_MASTER
WHERE TRIM(MATERIAL) = TRIM(:material)
ORDER BY PLNT, SLOC;

SELECT COUNT(*) AS MATCHING_ROWS,
       SUM(CASE WHEN SPECIAL_CONTROL_FLAG = 'HVP' THEN 1 ELSE 0 END) AS HVP_ROWS,
       SUM(CASE WHEN SPECIAL_CONTROL_FLAG IS NULL THEN 1 ELSE 0 END) AS BLANK_ROWS
FROM MATERIAL.MAT_MASTER
WHERE TRIM(MATERIAL) = TRIM(:material);
